// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5pEHWCoIJVR5l1N2cQ24uSBH2jY4n140',
    appId: '1:209489509394:web:8d4c0d4293c4b1b9956ccb',
    messagingSenderId: '209489509394',
    projectId: 'brotherz-score',
    authDomain: 'brotherz-score.firebaseapp.com',
    storageBucket: 'brotherz-score.firebasestorage.app',
    measurementId: 'G-LKZTV6X63C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq37cP5jJo1fjhtyYfyHf0mhmnqkWurwo',
    appId: '1:209489509394:android:c17ea9c26fab8bf2956ccb',
    messagingSenderId: '209489509394',
    projectId: 'brotherz-score',
    storageBucket: 'brotherz-score.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HJyyJjrnAmR4EwZYqUTaQRV0dXezvSA',
    appId: '1:209489509394:ios:809684d5819641a0956ccb',
    messagingSenderId: '209489509394',
    projectId: 'brotherz-score',
    storageBucket: 'brotherz-score.firebasestorage.app',
    iosBundleId: 'com.example.brothersScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_HJyyJjrnAmR4EwZYqUTaQRV0dXezvSA',
    appId: '1:209489509394:ios:809684d5819641a0956ccb',
    messagingSenderId: '209489509394',
    projectId: 'brotherz-score',
    storageBucket: 'brotherz-score.firebasestorage.app',
    iosBundleId: 'com.example.brothersScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5pEHWCoIJVR5l1N2cQ24uSBH2jY4n140',
    appId: '1:209489509394:web:368c979c4a93033f956ccb',
    messagingSenderId: '209489509394',
    projectId: 'brotherz-score',
    authDomain: 'brotherz-score.firebaseapp.com',
    storageBucket: 'brotherz-score.firebasestorage.app',
    measurementId: 'G-D1BRD03K7F',
  );
}
