 import 'package:flutter_bloc/flutter_bloc.dart';
import '../../models/match_model.dart';
import '../../models/player_model.dart';
import '../../models/ball_event_model.dart';
import '../../repositories/match_repository.dart';
import 'match_state.dart';

class MatchCubit extends Cubit<MatchState> {
  final MatchRepository _repository;

  MatchCubit(this._repository) : super(MatchInitial());

  // ── Match Creation Wizard ──────────────────────────────────────────────────

  MatchSetupStep1Complete? _step1Data;
  final List<PlayerModel> _teamAPlayers = [];
  final List<PlayerModel> _teamBPlayers = [];

  void saveStep1({
    required String matchName,
    required String teamAName,
    required String teamBName,
    required int overs,
  }) {
    _step1Data = MatchSetupStep1Complete(
      matchName: matchName,
      teamAName: teamAName,
      teamBName: teamBName,
      overs: overs,
    );
    _teamAPlayers.clear();
    _teamBPlayers.clear();
    emit(_step1Data!);
  }

  void addPlayerToSetup(PlayerModel player) {
    if (player.teamId == 'A') {
      _teamAPlayers.add(player);
    } else {
      _teamBPlayers.add(player);
    }
  }

  void completeStep2() {
    if (_step1Data != null) {
      emit(MatchSetupStep2Complete(_step1Data!));
    }
  }

  Future<void> saveMatch() async {
    if (_step1Data == null) {
      emit(const MatchError('Missing match details'));
      return;
    }
    if (_teamAPlayers.isEmpty || _teamBPlayers.isEmpty) {
      emit(const MatchError('Both teams must have at least 1 player'));
      return;
    }

    emit(MatchLoading());
    try {
      // Prepare participant IDs for fast index-free search
      final playerIds = [
        ..._teamAPlayers.map((p) => p.globalPlayerId ?? p.id),
        ..._teamBPlayers.map((p) => p.globalPlayerId ?? p.id),
      ].where((id) => id.isNotEmpty).toList();

      final match = MatchModel(
        id: '', // Generated by Firestore
        matchName: _step1Data!.matchName,
        teamAName: _step1Data!.teamAName,
        teamBName: _step1Data!.teamBName,
        overs: _step1Data!.overs,
        status: 'live',
        playerIds: playerIds,
        createdAt: DateTime.now(),
      );

      final matchId = await _repository.createMatch(match);

      // Save players
      for (final player in [..._teamAPlayers, ..._teamBPlayers]) {
        String globalId = player.globalPlayerId ?? '';
        if (globalId.isEmpty) {
          // New player added during match setup, create global record
          final globalRef = _repository.db.collection('players').doc();
          globalId = globalRef.id;
          await globalRef.set(player.copyWith(id: globalId, globalPlayerId: globalId).toFirestore());
        }
        await _repository.addPlayer(player.copyWith(matchId: matchId, globalPlayerId: globalId));
      }

      emit(MatchCreated(matchId));
    } catch (e) {
      emit(MatchError('Failed to create match: $e'));
    }
  }

  void resetWizard() {
    _step1Data = null;
    _teamAPlayers.clear();
    _teamBPlayers.clear();
    emit(MatchInitial());
  }

  // ── Live Scoring Actions ───────────────────────────────────────────────────

  Future<void> recordBall(BallEvent event) async {
    try {
      await _repository.recordBallEvent(event);
    } catch (e) {
      emit(MatchError('Failed to record ball: $e'));
    }
  }
}
